-- Deprecated.
-- Telegram destinations are now configured per region in Admin Settings and
-- stored encrypted in telegram_region_secrets.
--
-- Apply supabase/migrations/20260811_06_private_telegram_secrets.sql, then use
-- Admin Settings -> Telegram Configuration by Region.
