-- Deprecated.
-- Telegram sending is handled by Supabase Edge Functions:
--   - telegram-notify
--   - telegram-reminders
--   - telegram-fuel-reports
--
-- Do not add bot tokens or chat IDs to SQL files. Configure encrypted
-- per-region destinations in Admin Settings instead.
